using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace IPCAUI.Transactions
{
    public partial class ContraVoucher : Form
    {
        public ContraVoucher()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            ItemsPopultate();
        }

        private void ItemsPopultate()
        {
            DataSets.ItemsLookupEdit.ItemsDataTable dt = new DataSets.ItemsLookupEdit.ItemsDataTable();

            //DataRow dr = dt.NewRow();

            //dr[0] = "ITEM1";
            //dr[1] = "Paste";
            //dr[2] = "0.0";
            //dr[3] = "dozen";

            DataSets.ItemsLookupEdit.ItemsRow dr=dt.NewItemsRow();

            dr[0] = "ITEM1";
            dr[1] = "Paste";
            dr[2] = "0.0";
            dr[3] = "dozen";

            dt.AddItemsRow(dr);
            DataSets.ItemsLookupEdit ds = new DataSets.ItemsLookupEdit();
            ds.Tables.Clear();

            ds.Tables.Add(dt);

            BindingSource src = new BindingSource();
            src.DataSource = ds.Tables[0];
            repositoryItemLookUpEdit1.DataSource = src;
            
        }
        private void ContraVoucher_Load(object sender, EventArgs e)
        {
            // TODO: This line of code loads data into the 'iPCADataSet.Approvers' table. You can move, or remove it, as needed.
         //   this.approversTableAdapter.Fill(this.iPCADataSet.Approvers);

        }

        private void btnQuit_Click(object sender, EventArgs e)
        {
            this.Close();
        }
        protected override bool ProcessCmdKey(ref Message msg, Keys keyData)
        {
            if (keyData == Keys.Escape)
            {
                this.Close();
                return true;
            }
            return base.ProcessCmdKey(ref msg, keyData);
        }

       
        private void repositoryItemLookUpEdit1_EditValueChanged(object sender, EventArgs e)
        {

        }
    }
}
